#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const PATIENT_ID = process.env.PATIENT_ID ?? "1234";
const DATA_DIR = process.env.PATIENT_DATA_LOCATION ?? path.join(ROOT, "data/CSVs");
const PROMPT_FILE = process.env.SYSTEM_PROMPT_LOCATION ?? path.join(ROOT, "data/system-prompt.txt");

const systemPrompt = fs.readFileSync(PROMPT_FILE, "utf-8");

const TIMESPANS = [
  "all_available",
  "past_1_month",
  "past_3_months",
  "past_6_months",
  "past_1_year",
  "past_2_years",
];

const patientData = {};
const available = [];
for (const ts of TIMESPANS) {
  try {
    patientData[ts] = fs.readFileSync(path.join(DATA_DIR, `${PATIENT_ID}_data_${ts}.csv`), "utf-8");
    available.push(ts);
  } catch {
    // file not found — skip
  }
}

const out = `// Auto-generated by scripts/bake.mjs — do not edit
export const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
export const PATIENT_DATA: Record<string, string> = ${JSON.stringify(patientData)};
export const AVAILABLE_TIMESPANS: string[] = ${JSON.stringify(available)};
`;

fs.writeFileSync(path.join(ROOT, "lib/baked.generated.ts"), out);
console.log(`Baked: prompt + ${available.length} timespans → lib/baked.generated.ts`);
